name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test-lint:
    name: ${{ matrix.os }} / Py ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Show Python version
        run: python -V

      - name: Install project (editable + dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Ruff (lint + format check)
        run: |
          ruff check .
          ruff format --check .

      - name: Mypy (soft fail for now)
        run: mypy .
        continue-on-error: true

      - name: Run tests (skip UI headless)
        run: pytest -q -k "not ui" --disable-warnings --maxfail=1
